### ISSUE TITLE
incognito blocker not working

### ISSUE THREAD

**Issue by ineedhelp132** [brismuth/incognito-blocker#3]
**Describe the bug**

**Expected behavior**

**Desktop (please complete the following information):**

**Additional context**

**Comment by brismuth** [comment]
Make sure you’ve gone into your extension preferences and enabled it to run on incognito tabs.

**Comment by ineedhelp132** [comment]
I’ve got a chromebook, I don’t know how to do that 😬

**Comment by brismuth** [comment]
Go to chrome://extensions in your browser, select this extension, and enable the extension to run in incognito mode.
