### ISSUE TITLE
Cannot block Incognito with Tor

### ISSUE THREAD

**Issue by pranavagrawal321** [brismuth/incognito-blocker#4]
So, the extension works well on Brave as it doesn't allow incognito tabs to open, but "incognito tab using tor" still works. Please find some solution to it.

**Comment by brismuth** [comment]
This extension doesn't support Brave at all. I've never listed as compatible with the Brave browser. You're welcome to investigate adding support yourself and submitting a pull request - the entirety of the code is right here:
https://github.com/brismuth/incognito-blocker/blob/master/src/background.js
